Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyCMS.Models
{
    public class Customer
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter name")]
        [StringLength(30, MinimumLength = 3)]
        public string Name { get; set; }

        [DisplayName("Mobile Number")]
        [Required(ErrorMessage = "Please enter Mobile Number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Invalid Phone number")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage = "Please enter Email")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter a valid e-mail adress")]
        public string Email { get; set; }

        [Compare("Email", ErrorMessage = "Email Mismatch")]
        public string ConfirmEmail { get; set; }

        [Required(ErrorMessage = "Please enter Date Of Birth")]
        [DataType(DataType.Date)]
        public DateTime DOB { get; set; }

        [Required(ErrorMessage = "Please enter a Password")]
        [DataType(DataType.Password)]
        [StringLength(100, MinimumLength = 8, ErrorMessage = "Password must contain 8 characters")]
        public string Password { get; set; }

        [Compare("Password", ErrorMessage = "Password mismatch")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
    }
}

Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyCMS.Models;

namespace MyCMS.Controllers
{
    public class CustomersController : Controller
    {
        private Context db = new Context();

        // GET: Customers
        public ActionResult Index()
        {
            ViewBag.Message = "Customers";
            return View(db.customers.ToList());
        }

        // GET: Customers/Details/5
        public ActionResult Details(int? id)
        {
            ViewBag.Message = "WELCOME";

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,PhoneNumber,Email,ConfirmEmail,DOB,Password,ConfirmPassword")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("CustLogin");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,PhoneNumber,Email,ConfirmEmail,DOB,Password,ConfirmPassword")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("CustomerDashboard",new { customer.Id});
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.customers.Find(id);
            db.customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult CustLogin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CustLogin(Customer cust)
        {
            using (Context con = new Context())
            {
                var CustDetails = con.customers.Where(x => x.Email == cust.Email && x.Password == cust.Password).FirstOrDefault();
                if (CustDetails == null)
                {
                    return HttpNotFound();

                }
                else
                {
                    Session["Id"] = CustDetails.Id;
                    return RedirectToAction("CustomerDashboard", "Customers");
                }
                //return View();
            }
        }

        public ActionResult CustomerDashboard()
        {
            Customer c = new Customer();
            c.Id = Convert.ToInt32(Session["Id"].ToString());
            if (Session["Id"] != null)
            {
                return View(c);
            }
            else
            {
                return RedirectToAction("CustLogin");
            }

        }
    }
}

Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyCMS.Models;

namespace MyCMS.Controllers
{
    public class MenusController : Controller
    {
        private Context db = new Context();
        [HandleError]
        // GET: Menus
        public ActionResult Index()
        {
            ViewBag.Message = "Menu";
            return View(db.menus.ToList());
        }

        [HandleError]
        public ActionResult ShowMenu()
        {
            ViewBag.Message = "Menu";
            return View(db.menus.ToList());
        }

        public ActionResult ShowMenuHome()
        {
            return View(db.menus.ToList());
        }

        // GET: Menus/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Menu menu = db.menus.Find(id);
                if (menu == null)
                {
                    return HttpNotFound();
                }
                return View(menu);
            }
            catch            
            {
                return View("MENU NOT FOUND");
            }
            
        }

        // GET: Menus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Menus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FoodId,FoodName,FoodPrice")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.menus.Add(menu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(menu);
        }

        // GET: Menus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FoodId,FoodName,FoodPrice")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(menu);
        }

        // GET: Menus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Menu menu = db.menus.Find(id);
            db.menus.Remove(menu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyCMS.Models;

namespace MyCMS.Controllers
{
    public class OrdersController : Controller
    {
        private Context db = new Context();

        // GET: Orders
        public ActionResult Index()
        {
            ViewBag.Message = "ORDERS HISTORY";
            var orders = db.orders.Include(o => o.cust).Include(o => o.menu).Include(o => o.vend);
            return View(orders.ToList());
        }

        public ActionResult AllOrders()
        {
            var orders = db.orders.Include(o => o.cust).Include(o => o.menu).Include(o => o.vend);
            return View(orders.ToList());
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Orders orders = db.orders.Find(id);
            if (orders == null)
            {
                return HttpNotFound();
            }
            return View(orders);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            ViewBag.CustId = new SelectList(db.customers, "Id", "Name");
            ViewBag.MenuId = new SelectList(db.menus, "FoodId", "FoodName","FoodPrice");
            ViewBag.VendId = new SelectList(db.vendors, "Id", "Name");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrdId,Quantity,TotalBill,Status,MenuId,CustId,VendId")] Orders orders)
        {
            if (ModelState.IsValid)
            {
                Menu m = db.menus.FirstOrDefault(model => model.FoodId == orders.MenuId);
                orders.TotalBill = orders.Quantity * m.FoodPrice;
                orders.Status = "PENDING";
                db.orders.Add(orders);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustId = new SelectList(db.customers, "Id", "Name", orders.CustId);
            ViewBag.MenuId = new SelectList(db.menus, "FoodId", "FoodName", orders.MenuId);
            ViewBag.VendId = new SelectList(db.vendors, "Id", "Name", orders.VendId);
            return View(orders);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Orders orders = db.orders.Find(id);
            if (orders == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustId = new SelectList(db.customers, "Id", "Name", orders.CustId);
            ViewBag.MenuId = new SelectList(db.menus, "FoodId", "FoodName", orders.MenuId);
            ViewBag.VendId = new SelectList(db.vendors, "Id", "Name", orders.VendId);
            return View(orders);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrdId,Quantity,TotalBill,Status,MenuId,CustId,VendId")] Orders orders)
        {
            if (ModelState.IsValid)
            {
                db.Entry(orders).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("AllOrders");
            }
            ViewBag.CustId = new SelectList(db.customers, "Id", "Name", orders.CustId);
            ViewBag.MenuId = new SelectList(db.menus, "FoodId", "FoodName", orders.MenuId);
            ViewBag.VendId = new SelectList(db.vendors, "Id", "Name", orders.VendId);
            return View(orders);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Orders orders = db.orders.Find(id);
            if (orders == null)
            {
                return HttpNotFound();
            }
            return View(orders);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Orders orders = db.orders.Find(id);
            db.orders.Remove(orders);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Customers/Create.cshtml
@model MyCMS.Models.Customer

@{
    Layout = null;
}

<!DOCTYPE html>

<html style="background-color:aquamarine">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Signup</title>
    <style>
        #Signup-div {
            position: absolute;
            left: 40%;
            top: 20%;
            border: 1px solid #ccc;
            padding: 10px 10px;
        }

        .field-validation-error {
            color: red;
        }
    </style>
</head>
<body>
    <div id="Signup-div">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <table>
            <tr>
                <td>@Html.LabelFor(model => model.Name)</td>
                <td>@Html.EditorFor(model => model.Name)</td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(model => model.Name)</td>
            </tr>
            <tr></tr>
            <tr>
                <td>@Html.LabelFor(model => model.PhoneNumber)</td>
                <td>@Html.EditorFor(model => model.PhoneNumber)</td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(model => model.PhoneNumber)</td>
            </tr>
            <tr></tr>
            <tr>
                <td>@Html.LabelFor(model => model.Email)</td>
                <td>@Html.EditorFor(model => model.Email)</td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(model => model.Email)</td>
            </tr>
            <tr></tr>
            <tr>
                <td>@Html.LabelFor(model => model.ConfirmEmail)</td>
                <td>@Html.EditorFor(model => model.ConfirmEmail)</td>
            </tr>

            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(model => model.ConfirmEmail)</td>
            </tr>
            <tr></tr>
            <tr>
                <td>@Html.LabelFor(model => model.DOB)</td>
                <td>@Html.EditorFor(model => model.DOB)</td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(model => model.DOB)</td>
            </tr>
            <tr></tr>
            <tr>
                <td>@Html.LabelFor(model => model.Password)</td>
                <td>@Html.EditorFor(model => model.Password)</td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(model => model.Password)</td>
            </tr>
            <tr></tr>
            <tr>
                <td>@Html.LabelFor(model => model.ConfirmPassword)</td>
                <td>@Html.EditorFor(model => model.ConfirmPassword)</td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ValidationMessageFor(model => model.ConfirmPassword)</td>
            </tr>
            <tr></tr>
            <tr>
                <td>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="SIGNUP" class="btn btn-default" />
                        </div>
                    </div>
                </td>
            </tr>

        </table>


    }
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    </div>


</body>
</html>

Views/Customers/CustLogin.cshtml
@model MyCMS.Models.Customer
@{
    Layout = null;
}

<!DOCTYPE html>

<html style="background-color:aquamarine">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CUSTOMER LOGIN</title>
    <style>
        #login-div {
            position: absolute;
            left: 40%;
            top: 40%;
            border: 1px solid #ccc;
            padding: 10px 10px;
        }

        .field-validation-error {
            color: red;
        }
    </style>
</head>
<body>
    <div id="login-div">
        @using (Html.BeginForm("CustLogin", "Customers", FormMethod.Post))
        {

            <table>
                <tr>
                    <td>@Html.LabelFor(model => model.Email)</td>
                    <td>@Html.EditorFor(model => model.Email)</td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.Email)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.Password)</td>
                    <td>@Html.EditorFor(model => model.Password)</td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.Password)</td>
                </tr>
                <tr>
                    <td>
                    </td>
                    <td>
                        <input type="submit" value="LOGIN" />
                        <input type="reset" value="CLEAR" />
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.ActionLink("SIGNUP","Create","Customers")
                    </td>
                </tr>
            </table>
        }
        <script src="~/Scripts/jquery-3.4.1.min.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    </div>


</body>
</html>

Views/Customers/CustomerDashboard.cshtml
@model MyCMS.Models.Customer
@{
    ViewBag.Title = "CustomerDashboard";
    
}

<title>CUSTOMER DASHBOARD</title>

<div class="navbar-fixed-top" >
    <button1>
        @Html.ActionLink("PROFILE", "Details", "Customers", new { Model.Id }, new { @class = "navbar-brand" })
    </button1>
    <button2>
        @Html.ActionLink("Menu", "ShowMenu", "Menus", new { area = "" }, new { @class = "navbar-brand" })

    </button2>
    <button4>
        @Html.ActionLink("Orders History", "Index", "Orders", new { area = "" }, new { @class = "navbar-brand" })

    </button4>
    <button3>
        @Html.ActionLink("LOGOUT", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
    </button3>
    
</div>
<img src="~/Content/food2.jpg" />

Views/Customers/Delete.cshtml
@model MyCMS.Models.Customer

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Customer</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.PhoneNumber)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ConfirmEmail)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ConfirmEmail)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DOB)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DOB)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Password)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Password)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ConfirmPassword)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ConfirmPassword)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Views/Customers/Details.cshtml
@model MyCMS.Models.Customer

@{
    Layout = null;
}

<!DOCTYPE html>
<h4>@ViewBag.Message</h4>
<html style="background-color:antiquewhite">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CUSTOMER DETAILS</title>
    
</head>
<body>
            
            <table>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Name)</td>
                    <td> : </td>
                    <td>@Html.DisplayFor(model => model.Name)</td>
                </tr>
                <tr></tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.PhoneNumber)</td>
                    <td> : </td>
                    <td>@Html.DisplayFor(model => model.PhoneNumber)</td>
                </tr>
                <tr></tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Email)</td>
                    <td> : </td>
                    <td>@Html.DisplayFor(model => model.Email)</td>
                </tr>
                <tr></tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.DOB)</td>
                    <td> : </td>
                    <td>@Html.DisplayFor(model => model.DOB)</td>
                </tr>
                <tr></tr>
            </table>
        
    <div>
        <button1 style="color:aquamarine">
            @Html.ActionLink("EDIT DETAILS", "Edit","Customers", new { Model.Id }, new { @class = "navbar-brand" }) 
        </button1>
        <br />
        <button2>
            @Html.ActionLink("BACK ", "CustomerDashboard","Customers", new { id = Model.Id })
        </button2>
    </div>
</body>
</html>

Views/Customers/Edit.cshtml
@model MyCMS.Models.Customer

@{
    Layout = null;
}

<!DOCTYPE html>

<html style="background-color:azure">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <style>
        #Edit-div {
            position: absolute;
            left: 40%;
            top: 20%;
            border: 1px solid #ccc;
            padding: 10px 10px;
        }

        .field-validation-error {
            color: red;
        }
    </style>
</head>
<body>
    <div id="Edit-div">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <table>
                <tr>
                    <td>@Html.LabelFor(model => model.Name)</td>
                    <td>@Html.EditorFor(model => model.Name)</td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.Name)</td>
                </tr>
                <tr></tr>
                <tr>
                    <td>@Html.LabelFor(model => model.PhoneNumber)</td>
                    <td>@Html.EditorFor(model => model.PhoneNumber)</td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.PhoneNumber)</td>
                </tr>
                <tr></tr>
                <tr>
                    <td>@Html.LabelFor(model => model.Email)</td>
                    <td>@Html.EditorFor(model => model.Email)</td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.Email)</td>
                </tr>
                <tr></tr>
                <tr>
                    <td>@Html.LabelFor(model => model.ConfirmEmail)</td>
                    <td>@Html.EditorFor(model => model.ConfirmEmail)</td>
                </tr>

                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.ConfirmEmail)</td>
                </tr>
                <tr></tr>
                <tr>
                    <td>@Html.LabelFor(model => model.DOB)</td>
                    <td>@Html.EditorFor(model => model.DOB)</td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.DOB)</td>
                </tr>
                <tr></tr>
                <tr>
                    <td>@Html.LabelFor(model => model.Password)</td>
                    <td>@Html.EditorFor(model => model.Password)</td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.Password)</td>
                </tr>
                <tr></tr>
                <tr>
                    <td>@Html.LabelFor(model => model.ConfirmPassword)</td>
                    <td>@Html.EditorFor(model => model.ConfirmPassword)</td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.ConfirmPassword)</td>
                </tr>
                <tr></tr>
                <tr>
                    <td>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="UPDATE" class="btn btn-default" />
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>

                </tr>
                <tr>
                    <td>
                        <button2>
                            @Html.ActionLink("BACK ", "Details", "Customers", new { id = Model.Id }, new { @class = "navbar-brand" })
                        </button2>
                    </td>
                </tr>

            </table>


        }
        <script src="~/Scripts/jquery-3.4.1.min.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    </div>


</body>
</html>